Avoid unused variable in DHCP lease finalize method
If the network DHCP lease support is not detected, the build
will generate a warning / error:

libvirt-gobject-network-dhcp-lease.c: In function 'gvir_network_dhcp_lease_finalize':
libvirt-gobject-network-dhcp-lease.c:99:27: error: unused variable 'lease' [-Werror=unused-variable]
     GVirNetworkDHCPLease *lease = GVIR_NETWORK_DHCP_LEASE(object);
                           ^~~~~
cc1: all warnings being treated as errors

Signed-off-by: Daniel P. Berrange <berrange@redhat.com>