Specify virtualization type in Python example
Without this creating the domain fails:

gi._glib.GError: Failed to create domain: internal error missing domain type attribute