event-test: LibvirtGLib.init() takes (at maximum) 1 argment
The previous behaviour with pygobject required 2 arguments to be passed
to LibvirtGLib.init().

As it's been changed, whenever we try to run event-test we'd get:
```
Using uri:qemu:///system
Traceback (most recent call last):
  File "event-test.py", line 62, in <module>
    main()
  File "event-test.py", line 51, in main
    LibvirtGLib.init(0, "")
TypeError: LibvirtGLib.init() takes exactly 1 argument (2 given)
```

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
Reviewed-by: Daniel P. Berrangé <berrange@redhat.com>
Reviewed-by: Michal Privoznik <mprivozn@redhat.com>