gobject: Drop some unused variables
After abe983ddf8a569 there are some variables, that are unused:

  CC       libvirt_gobject_1_0_la-libvirt-gobject-domain-disk.lo
  CC       libvirt_gobject_1_0_la-libvirt-gobject-domain-interface.lo
  CC       libvirt_gobject_1_0_la-libvirt-gobject-domain.lo
  CC       libvirt_gobject_1_0_la-libvirt-gobject-interface.lo
../../libvirt-gobject/libvirt-gobject-domain-interface.c: In function 'gvir_domain_interface_finalize':
../../libvirt-gobject/libvirt-gobject-domain-interface.c:54:26: error: unused variable 'self' [-Werror=unused-variable]
     GVirDomainInterface *self = GVIR_DOMAIN_INTERFACE(object);
                          ^
cc1: all warnings being treated as errors
Makefile:724: recipe for target 'libvirt_gobject_1_0_la-libvirt-gobject-domain-interface.lo' failed
make[3]: *** [libvirt_gobject_1_0_la-libvirt-gobject-domain-interface.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
../../libvirt-gobject/libvirt-gobject-domain-disk.c: In function 'gvir_domain_disk_finalize':
../../libvirt-gobject/libvirt-gobject-domain-disk.c:54:21: error: unused variable 'self' [-Werror=unused-variable]
     GVirDomainDisk *self = GVIR_DOMAIN_DISK(object);
                     ^
cc1: all warnings being treated as errors
Makefile:717: recipe for target 'libvirt_gobject_1_0_la-libvirt-gobject-domain-disk.lo' failed

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>